config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'location#index'
  resources :users, only: [:new, :create, :show]
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  resources :cards
  get "/closest-points" => "location#closest" #query lat=1234&long=1234
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	belongs_to :user
	has_many :spendings

	validates :name, presence: true
	validates :serial_num, presence: true, numericality: true, length: {is: 8}
	validates :verification_num, presence: true, numericality: true, length: {is: 3}
	validates :reminder_amount, presence: true,
	numericality: {greater_than_or_equal_to: 0 }

	# def encrypt(serial, verfication)
	# 	@@crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
	# 	encrypted_serial = @@crypt.encrypt_and_sign(serial)
	# end

	def card_num_changed
		(self.serial_num_changed? || self.verification_num_changed?) && !self.new_record?
	end

	def get_balance
		agent = Mechanize.new
		page = agent.get("https://www.orcacard.com/ERG-Seattle/p4_017.do")
		form = page.form('p4_006Form')
		form.cardNumber = self.serial_num
		form.cardVerificationNumber = self.verification_num
		page2 = agent.submit(form, form.buttons.first)
		# check for errors
		if(page2.search(".error").length > 0)
			return false
		end
		form2 = page2.form('p7_025Form')
		page3 = agent.submit(form2, form2.buttons.first)
		balance = page3.search('td').children.first.text
		balance = balance[1..-1].to_f
		self.update({balance: balance})
		balance
	end

	def send_reminder
		if(self.email_reminder)
			UserMailer.reminder(self.user, self).deliver!
		elsif(self.text_reminder)
			#send text
		end
	end

	def self.update_task
		@cards = Card.all
		@cards.each do |card|
			new_balance = card.get_balance
			if new_balance && (new_balance <= card.reminder_amount)
					card.send_reminder
			end
		end
	end
end

app/models/location.rb
require "#{Rails.root}/lib/get_distance"
require "#{Rails.root}/lib/max_heap"

class Location < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	NUM_RESULTS = 5

	def self.get_closest(long, lat)
		# get closest results
		# uses maxheap
		query = {longitude: long.to_f, latitude: lat.to_f}
		top5 = Maxheap.new(NUM_RESULTS, "distance")
		Location.all.each do |loc|
			dist = Distance.get_distance(loc, query)
			top5.add({location: loc, distance: dist})
		end
		return top5.elements.sort_by{ |obj| obj[:distance]}
	end

end

app/models/spending.rb
class Spending < ApplicationRecord
	belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
has_many :cards
attr_accessor :password
validates_confirmation_of :password
before_save :encrypt_password

validates :username, presence: true
validates :password, presence: true

def encrypt_password
	self.password_salt = BCrypt::Engine.generate_salt
	self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
end

def self.authenticate(username, password)
	user = User.where(username: username).first
	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
		user
	else
		nil
	end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def new
		@card = Card.new
	end

	def create
		#encrypt serial and verification nums
		@card = Card.new(card_params)
		@card.user_id = current_user.id
		if(@card.save)
			@card.get_balance
			redirect_to current_user
		else
			render :new
		end
	end

	def show
		@card = Card.find(params[:id])
	end

	def edit
		@card = Card.find(params[:id])
	end

	def update
		@card = Card.find(params[:id])
		serial_num = @card.serial_num
		verification_num = @card.verification_num
		if @card.update(card_params)
				if serial_num != @card.serial_num || verification_num != @card.verification_num
					@card.get_balance
				end
				redirect_to current_user
		else
			render :edit
		end
	end

	private
	def card_params
		params.require(:card).permit(:name, :serial_num, :verification_num, :reminder_amount, :email_reminder, :text_reminder)
	end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
	def index
		@locations = Location.all
	end

	def closest
		if(params[:long] && params[:lat])
			locations = Location.get_closest(params[:long], params[:lat])
			respond_to do |format|
				format.json{ render json: locations}
			end
		else
			render nothing: true, status: 400
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		#redirect to show page if already signed in
		redirect_to current_user if current_user
	end

	def create
		@user = User.authenticate(params[:username], params[:password])
		if @user
			session[:user_id] = @user.id
			redirect_to @user
		else
			flash[:alert] = "There was a problem logging you in"
			redirect_to log_in_path
		end 
	end

	def destroy
		session[:user_id] = nil
		redirect_to "/"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if(@user.save)
			session[:user_id] = @user.id
			redirect_to @user
		else
			flash[:alert] = "There was a problem creating your account. Please try again."
			render :new
		end
	end

	def show
		if session[:user_id] && session[:user_id] == params[:id].to_i
			@user = current_user
		else
			redirect_to log_in_path
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username, :phone)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card_form.html.erb
	<%= form_for card do |f| %>
		<div class="form-group">
			<%= f.label :name, "Give your card a name" %>
			<%= f.text_field :name, {class: "form-control", autofocus: true } %>
			<%= render partial: "form_error", :locals => {:resource => card, :attribute => "name"} %>
		</div>
		<div class="form-group">
			<%= f.label :serial_num, "Serial number" %>
			<%= f.text_field :serial_num, class: "form-control" %>
			<small id="serialNumHelp" class="form-text">Bottom left corner of card</small>
			<%= render partial: "form_error", :locals => {:resource => card, :attribute => "serial_num", :attribute_display => "Serial number"} %>
		</div>
		<div class="form-group">
			<%= f.label :verification_num, "Verification number" %>
			<%= f.text_field :verification_num, class: "form-control" %>
			<small id="verificationNumHelp" class="form-text">Bottom right corner of card</small>
			<%= render partial: "form_error", :locals => {:resource => card, :attribute => "verification_num", :attribute_display => "Verification number"} %>
		</div>
		<div class="form-group">
			<%= f.label :reminder_amount, "Remind me when balance gets below " %>
			<div class="input-group">
			<span class="input-group-addon">$</span>
			<%= f.text_field :reminder_amount, class: "form-control" %>
			</div>
			<%= render partial: "form_error", :locals => {:resource => card, :attribute => "reminder_amount", :attribute_display => "Reminder amount"} %>
		</div>
		<div class="form-group">
			<%= f.label :email_reminder, "By email" %>
			<%= f.check_box :email_reminder %>
			<%= f.label :text_reminder, "By text" %>
			<%= f.check_box :text_reminder %>
		</div>
		<%= f.submit button_text %>
	<% end %>

app/views/cards/_form_error.html.erb
<% if !resource.errors[attribute.to_sym].empty? %>
	<% attribute_display = attribute_display || attribute %>
	<small class="form-text error-text"><%= attribute_display + " " + resource.errors[attribute.to_sym][0] %></small>
<% end %>

app/views/cards/edit.html.erb
<div class="container">
	<div class="div-3">
	</div>
	<div class="div-6">
			<%= render partial: "card_form", :locals=>{
				:card => @card, :button_text => "Edit card"} %>
	</div>
	<div class="div-3">
	</div>
</div>

app/views/cards/new.html.erb
<div class="container">
<div class="div-3">
</div>
<div class="div-6">
		<%= render partial: "card_form", :locals=>{
			:card => @card, :button_text => "Register card"} %>
</div>
<div class="div-3">
</div>
</div>

app/views/cards/show.html.erb
<div class="container">
	<h4>Card name: <%= @card.name %></h4>
	<%= link_to "edit", edit_card_path(@card) %>
	<ul class="card-details">
		<li>Serial number: <%= @card.serial_num %></li>
		<li>Verification number: <%= @card.verification_num %></li>
		<li>Reminder amount: <%= number_to_currency(@card.reminder_amount) %></li>
		<li>Email reminders: <%= @card.email_reminder ? "Yes" : "No" %></li>
		<li>Text reminders: <%= @card.text_reminder ? "Yes" : "No" %></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrcaRefill</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src=<%= "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_api_key}" %> defer></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/location/index.html.erb
<header class="header desktop">
	<div class="div-4">
	  <h1>orca refill</h1>
	</div>
	<div class="text-center div-4 desktop">
	</div>
	<div class="text-center div-4 header-btn">
	   <%= link_to "check my card", log_in_path, :class => "btn btn-primary" %>
	</div>
</header>
<%= react_component('App', {locations: @locations},{class: "main"}) %>
<footer>
	<div class="div-4">
	</div>
	<div class="text-center div-4 desktop">
	  <h4>click a pin for directions</h4>
	</div>
	<div class="text-center div-4 header-btn">
	</div>
</footer>

app/views/users/_card.html.erb
<h4><%= link_to card.name, card %></h4>
<% if card.balance %>
	<p>Balance: <%=number_to_currency(card.balance) %></p>
<% else %>
	<p>We could not find your balance. Check that your <%= link_to "card info", card %> is correct.</p>
<% end %>
<% if card.reminder_amount %>
<p>Reminder when balance gets below: <%=number_to_currency(card.reminder_amount) %></p>
<% end %>

app/views/users/new.html.erb
<div class="container">
	<div class="div-3">
	</div>
	<div class="div-6">
		<p>Already have an account? <%= link_to "Log in", log_in_path %></p>
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%=f.label :username %>
				<%=f.text_field :username, {class: "form-control", autofocus: true } %>
				<% if !@user.errors[:username].empty? %>
					<small class="form-text error-text">Username <%= @user.errors[:username][0] %></small>
				<% end %>
			</div>
			<div class="form-group">
				<%=f.label :email %>
				<%=f.text_field :email, class: "form-control" %>
				<small id="emailHelp" class="form-text">If you want to get email reminders</small>
			</div>
			<div class="form-group">
				<%=f.label :phone %>
				<%=f.text_field :phone, class: "form-control" %>
				<small id="phoneHelp" class="form-text">If you want to get text reminders</small>
			</div>
			<div class="form-group">
				<%=f.label :password %>
				<%=f.password_field :password, class: "form-control" %>
				<% if !@user.errors[:password].empty? %>
					<small class="form-text error-text">Password <%= @user.errors[:password][0] %></small>
				<% end %>
			</div>
			<div class="form-group">
				<%=f.label :password_confirmation %>
				<%=f.password_field :password_confirmation, class: "form-control" %>
				<% if !@user.errors[:password_confirmation].empty? %>
					<small class="form-text error-text">Password Confirmation <%= @user.errors[:password_confirmation][0] %></small>
				<% end %>
			</div>
			<%=f.submit "Sign Up"%>
		<%end %>
	</div>
	<div class="div-3">
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<h3>Welcome, <%=@user.username%></h3>
	<ul class="nav nav-pills">
	  <li class="nav-item active"><%= link_to "My cards", @user, class: "nav-link" %></li>
	   <li class="nav-item active"><%= link_to "Register a card", new_card_path, class: "nav-link" %></li>
	  <li class="nav-item"><%= link_to "Map", root_path, class: "nav-link" %></li>
	  <li class="nav-item"><%= link_to "Logout", log_out_path, class: "nav-link" %></li>
	</ul>
	<ol>
	<% @user.cards.each do |card| %>
		<li><%= render :partial=>"card", :locals=>{:card => card} %></li>
	<% end %>
	</ol>
</div>